# Generated by Django 6.0.4 on 2026-04-21 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda', 'Boda-boda')], max_length=50)),
                ('day_rate', models.IntegerField()),
                ('night_rate', models.IntegerField()),
                ('short_stay_rate', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('model_color', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_status', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory')),
            ],
        ),
    ]
