# Generated by Django 6.0.4 on 2026-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='model_color',
            new_name='color',
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
