# Generated by Django 6.0.4 on 2026-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_model_color_vehicleregistration_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={},
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='status',
            field=models.CharField(choices=[('parked', 'Parked'), ('signed_out', 'Signed Out')], default='parked', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda', 'Boda-boda')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='driver_status',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
