# Generated by Django 6.0.4 on 2026-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_vehicleregistration_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('short', 'Short Stay')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'truck'), ('Personal car', 'personal car'), ('Taxi', 'taxi'), ('coaster', 'coaster'), ('Boda-boda', 'boda-boda')], max_length=50, unique=True),
        ),
    ]
