# Generated by Django 6.0.4 on 2026-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_vehicleregistration_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Personal car', 'Personal car'), ('Taxi', 'Taxi'), ('Coaster', 'Coaster'), ('Boda-boda', 'Boda-boda')], max_length=50, unique=True),
        ),
    ]
