# Generated by Django 6.0.4 on 2026-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_vehiclecategory_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('short', 'Short Stay'), ('overstay', 'Overstay')], max_length=10, null=True),
        ),
    ]
