# Generated by Django 6.0.4 on 2026-04-21 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.IntegerField()),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='parking.vehicleregistration')),
            ],
        ),
    ]
