# Generated by Django 6.0.4 on 2026-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='name',
            field=models.CharField(choices=[('pressure', 'Tyre Pressure'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
