# Generated by Django 6.0.4 on 2026-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceprice_model_serviceprice_vehicle_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='model',
        ),
        migrations.RemoveField(
            model_name='serviceprice',
            name='vehicle_size',
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
